Repository bobmazy/ai-hackathon, pull requests merged in 2023-05, with the labels that each got.

#1 Feature/add new data sources
  .env.sample
  .gitignore
  README.md
  data/common/countTokens.ts
  data/common/types.ts
  data/confluence/cf-chunk-creation.ts
  data/confluence/cf-http-client-factory.ts
  data/confluence/cf-http-get.ts
  data/confluence/models/ConfluencePage.ts
  data/confluence/models/ConfluencePagesDto.ts
  data/create-embeddings.ts
  data/embeddings-creation.ts
  data/microsoft/ms-graph-auth.ts
  data/microsoft/ms-graph-http-client-factory.ts
  data/microsoft/people/models/MS_PeopleDto.ts
  data/microsoft/people/models/MS_Person.ts
  data/microsoft/people/people-chunk-creation.ts
  data/microsoft/people/people-http-get.ts
  data/miro/miro-chunk-creation.ts
  data/miro/miro-data-parser.ts
  data/miro/models/MiroItem.ts
  data/miro/src/miro-source.csv
  data/read-sp-data.ts
  data/sharepoint/models/SpPage.ts
  data/sharepoint/models/SpPagesDto.ts
  data/sharepoint/sp-chunk-creation.ts
  data/sharepoint/sp-http-client-factory.ts
  data/sharepoint/sp-http-get.ts
  data/types.ts
  package.json
  src/SystemPromptInfos.ts
  src/chat.ts
  src/open-api/open-api-factory.ts
Labels: enhancement

#2 fix confluence link
  data/confluence/models/ConfluencePage.ts
  data/confluence/models/ConfluencePagesDto.ts
Labels: bug

#3 Bugfix/fix miro link
  .env.sample
  src/SystemPromptInfos.ts
Labels: bug

#4 improve content of people chunk
  data/embeddings-creation.ts
  data/microsoft/people/people-chunk-creation.ts
  data/miro/miro-chunk-creation.ts
  package.json
  src/SystemPromptInfos.ts
Labels: enhancement

#6 integrate github
  .env.sample
  data/common/strUtils.ts
  data/common/types.ts
  data/embeddings-creation.ts
  data/github/gh-chunk-creation.ts
  data/github/gh-http-client-factory.ts
  data/github/gh-http-get.ts
  data/github/models/GitHubRepo.ts
  data/github/models/GitHubRepoContributor.ts
  data/github/models/GitHubRepoReadme.ts
  data/github/models/GitHubUser.ts
  package.json
  src/SystemPromptInfos.ts
Labels: enhancement

#8 fix separating char
  data/miro/src/miro-source.csv
Labels: bug

#9 create a single embeddings json for each data resource (to improve perfomance, etc)
  data/common/coloredLog.ts
  data/common/saveDataToFile.ts
  data/confluence/cf-chunk-creation.ts
  data/confluence/cf-embeddings-creation.ts
  data/embeddings-creation.ts
  data/github/gh-chunk-creation.ts
  data/github/gh-embeddings-creation.ts
  data/microsoft/people/people-chunk-creation.ts
  data/microsoft/people/people-embeddings-creation.ts
  data/miro/miro-chunk-creation.ts
  data/miro/miro-data-parser.ts
  data/miro/miro-embeddings-creation.ts
  data/miro/src/miro-source.csv
  data/sharepoint/sp-chunk-creation.ts
  data/sharepoint/sp-embeddings-creation.ts
  package.json
  src/chat.ts
Labels: 🎨refactoring
